spring:
  application:
    name: company-service
  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:8888
eureka:
  instance:
    hostname: ${EUREKA_SERVER_HOST:localhost}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:8761/eureka/
application:
  user-service-url: http://${GATEWAY_SERVER_HOST:localhost}:8282/api/v1/users