spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:8888
eureka:
  instance:
    hostname: ${EUREKA_SERVER_HOST:localhost}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:8761/eureka/
