spring:
  datasource:
    url: jdbc:h2:mem:companies
    username: root
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
server:
  port: 8070